# Generated by Django 3.2 on 2021-04-15 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profecture',
            new_name='prefecture',
        ),
    ]
